api/urls.py
from django.urls import path

from .views import DomainDetailApiView

urlpatterns= [

    path('domain', DomainDetailApiView.as_view(), name="domain_detail")
]

domain/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.db.models import Q
from django.dispatch import receiver
from django.core.exceptions import ValidationError
from django.conf import settings
from django.core.validators import URLValidator
from  _sha256 import sha256
import requests
# Create your models here.


LIST_CHOICES = (
    (0, 'blacklist'),
    (1, 'whitelist'),
)

def domain_validator(value):
    qs = Domain.objects.filter(domain_name__iexact=value)
    if qs.exists():
        raise ValidationError(f"This domain already exists within \"{qs.first().list.name}\" which belongs to device \"{qs.first().list.device.name}\"")


class Device(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class List(models.Model):
    name                = models.CharField(max_length=100)
    short_description   = models.TextField(blank=True)
    device              = models.ForeignKey(Device, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Domain(models.Model):

    domain_name     = models.URLField()
    category        = models.SmallIntegerField(choices=LIST_CHOICES, default=0)
    list            = models.ForeignKey(List, on_delete=models.CASCADE)
    virustotal      = models.TextField(blank=True)
    sha256_hash     = models.CharField(max_length=64, unique=True, blank=True)

    def __str__(self):
        return self.domain_name

    def get_data(self):
        url = f"https://www.virustotal.com/ui/urls/{self.sha256_hash}?relationships=network_location%2Clast_serving_ip_address"
        data = requests.get(url).json()['data']['attributes']
        print(f"https://www.virustotal.com/ui/urls/{self.sha256_hash}/network_location")
        whois = requests.get(f"https://www.virustotal.com/ui/urls/{self.sha256_hash}/network_location").json()['data']['attributes'].get('whois', 'No data')
        engines = data['last_analysis_results']
        summary = data['last_analysis_stats']
        result = {**engines, 'whois': whois, "summary": {**summary}}
        return result

    # def get_data(self):
    #     url = "https://openpagerank.com/api/v1.0/getPageRank/"
    #     a = requests.get(url, headers={"API-OPR": settings.DOMAIN_API_KEY}, params={'domains[]': [self.domain_name]})
    #     return a.json()["response"]

    def get_whois(self):
        whois = requests.get(f"https://www.virustotal.com/ui/urls/{self.sha256_hash}/network_location").\
            json()['data']['attributes']['whois']

    def clean(self):
        if self.pk:
            qs = Domain.objects.filter(Q(domain_name=self.domain_name) & ~Q(id=self.id))
        else:
            qs = Domain.objects.filter(domain_name__iexact=self.domain_name)
        if qs.exists():
            raise ValidationError(
                f"This domain already exists within \"{qs.first().list.name}\" which belongs to device "
                f"\"{qs.first().list.device.name}\"")


@receiver(pre_save, sender=Domain)
def generate_sha256(sender, instance, **kwargs):
    if  not instance.domain_name.endswith('/'):
        instance.domain_name += '/'
    instance.sha256_hash = sha256(bytes(instance.domain_name, 'utf-8')).hexdigest()
    instance.virustotal = instance.get_data()

templates/base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Black or white</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    {% block styles %}

    {% endblock %}
</head>
<body>
    <div class="container">
        <div class="sidebar">
            <div class="folder-wrap">
                <input type="checkbox" class="menu-expand">
                <div class="menu-header">Menu</div>
                <div class="menu-folder">
                    <div class="menu-entry menu-entry-content">
                        <img src="{% static 'img/icons/icons8-plus-48.png' %}">
                        <div class="device-description">Add single domain</div> 
                    </div>
                    <div class="menu-entry menu-entry-content">
                        <img src="{% static 'img/icons/icons8-list-view-48.png' %}">
                        <a href="{% url "list_upload" %}" >
                            <div class="device-description">Import list of domains</div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="folder-wrap">
                <input type="checkbox" class="menu-expand">
                <div class="menu-header">Devices</div>
                <div class="menu-folder">
                    {% for device in devices %}
                        <div class="menu-entry">
                            <input type="checkbox" class="menu-expand">
                            <div class="menu-header menu-entry-content">
                                <img src="{% static 'img/icons/icons8-server-48.png' %}">
                                <div class="device-description">{{ device.name }}</div>  
                            </div>
                            <div class="menu-folder">
                                {% for list in device.list_set.all %}
                                    <div class="menu-entry menu-entry-content no-icon">{{ list }}</div>
                                {% endfor %}

{#                                <div class="menu-entry menu-entry-content no-icon">List 2</div>#}
{#                                <div class="menu-entry menu-entry-content no-icon">List 3</div>#}
                                <div class="menu-entry menu-entry-content no-icon">New list...</div>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="menu-entry">
                        <div class="menu-entry-content">
                            <img src="{% static 'img/icons/icons8-server-48.png' %}">
                            <div class="device-description">New device...</div>  
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="main">
        {% block content %}

        {% endblock %}
        <a href="https://icons8.com">Icon pack by Icons8</a>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    {% block javascript %}
    {% endblock %}

</body>
</html>

templates/device_createform.html
<form action="{% if form.instance.pk %}{% url 'device_update' %}{% else %}{% url 'device_create' %}{% endif %}" method="post">
    {{ form.name.errors }}
    {{ form.name.label }} {{ form.name }}
    <button>Submit</button>
</form>

templates/domain_list.html
{% extends 'base.html' %}
{% load static %}



{% block content %}



    <div class="input-container">
        <div class="input-header">Wprowadź domenę i sprawdź jej wiarygoność</div>
        <form action="#">
            <div class="input-field">
                <button class="input-icon">
                    <img src="{% static 'img/icons/icons8-search-48.png' %}">
                </button>
                <input type="text">
            </div>
        </form>
    </div>
    <div class="results-container">
        <div class="results-bar state-ok">OK</div>
        <!-- <div class="results-bar state-warning">Potencjalnie niebezpieczna</div> -->
        <!-- <div class="results-bar state-danger">Niebezpieczna</div> -->

        <div class="results-header">Wyniki wyszukiwania dla domeny http://lalproject.pl</div>
        <div class="results-items">
            <div class="results-item">
                <div class="result-item-header">Wyniki z silników antywirusowych</div>
                <div class="result-item-subheader">(kliknij aby zobaczyć szczegóły)</div>
                <div class="stats">
                    <div class="stat stat-ok" onclick="openModal(this)">
                        <div class="stat-icon"><img src="{% static 'img/icons/icons8-happy-48.png' %}"></div>
                        <div class="stat-desc">Bezpieczne</div>
                        <div class="stat-val">30 (60%)</div>
                    </div>
                    <div class="modal">
                        <div class="modal-wrapper">
                            <div class="modal-content">
                                <div class="modal-header stat-ok">
                                    Witryny uznające domenę http://lalproject.pl za bezpieczną.
                                </div>
                                <ul class="modal-list">
                                    <li>ADMINUSLabs</li>
                                    <li>AegisLab WebGuard</li>
                                    <li>AlienVault</li>
                                    <li>Antiy-AVL</li>
                                    <li>Avira</li>
                                    <li>Baidu-International</li>
                                    <li>BitDefender</li>
                                    <li>Blueliv</li>
                                </ul>
                                <div class="modal-close" onclick="closeModal(this)"><img
                                        src="{% static 'img/icons/icons8-cancel-48.png' %}"></div>
                            </div>
                        </div>
                    </div>
                    <div class="stat stat-warning" onclick="openModal(this)">
                        <div class="stat-icon"><img src="{% static 'img/icons/icons8-boring-48.png' %}"></div>
                        <div class="stat-desc">Podejrzane</div>
                        <div class="stat-val">13 (26%)</div>
                    </div>
                    <div class="modal">
                        <div class="modal-wrapper">
                            <div class="modal-content">
                                <div class="modal-header stat-warning">
                                    Witryny uznające domenę http://lalproject.pl za podejrzaną.
                                </div>
                                <ul class="modal-list">
                                    <li>ADMINUSLabs</li>
                                    <li>AegisLab WebGuard</li>
                                    <li>AlienVault</li>
                                    <li>Antiy-AVL</li>
                                    <li>Avira</li>
                                    <li>Baidu-International</li>
                                    <li>BitDefender</li>
                                    <li>Blueliv</li>
                                </ul>
                                <div class="modal-close" onclick="closeModal(this)"><img
                                        src="{% static 'img/icons/icons8-cancel-48.png' %}"></div>
                            </div>
                        </div>
                    </div>
                    <div class="stat stat-danger" onclick="openModal(this)">
                        <div class="stat-icon"><img src="{% static 'img/icons/icons8-sad-48.png' %}"></div>
                        <div class="stat-desc">Niebezpieczne</div>
                        <div class="stat-val">5 (10%)</div>
                    </div>
                    <div class="modal">
                        <div class="modal-wrapper">
                            <div class="modal-content">
                                <div class="modal-header stat-danger">
                                    Witryny uznające domenę http://lalproject.pl za niebezpieczną.
                                </div>
                                <ul class="modal-list">
                                    <li>ADMINUSLabs</li>
                                    <li>AegisLab WebGuard</li>
                                    <li>AlienVault</li>
                                    <li>Antiy-AVL</li>
                                    <li>Avira</li>
                                    <li>Baidu-International</li>
                                    <li>BitDefender</li>
                                    <li>Blueliv</li>
                                </ul>
                                <div class="modal-close" onclick="closeModal(this)"><img
                                        src="{% static 'img/icons/icons8-cancel-48.pn' %}g"></div>
                            </div>
                        </div>
                    </div>
                    <div class="stat" onclick="openModal(this)">
                        <div class="stat-icon"><img src="{% static 'img/icons/icons8-puzzled-48.png' %}"></div>
                        <div class="stat-desc">Niezbadane</div>
                        <div class="stat-val">2 (4%)</div>
                    </div>
                    <div class="modal">
                        <div class="modal-wrapper">
                            <div class="modal-content">
                                <div class="modal-header">
                                    Witryny które nie zbadały domeny http://lalproject.pl.
                                </div>
                                <ul class="modal-list">
                                    <li>ADMINUSLabs</li>
                                    <li>AegisLab WebGuard</li>
                                    <li>AlienVault</li>
                                    <li>Antiy-AVL</li>
                                    <li>Avira</li>
                                    <li>Baidu-International</li>
                                    <li>BitDefender</li>
                                    <li>Blueliv</li>
                                </ul>
                                <div class="modal-close" onclick="closeModal(this)"><img
                                        src="{% static 'img/icons/icons8-cancel-48.png' %}"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="results-item">
                <div class="result-item-header">Wyniki zapytania whois</div>
            </div>
            <div class="results-item">
                <div class="result-item-header">Wyniki jakiegoś tam czegoś</div>
            </div>
        </div>
        <div class="results-buttons">
            <button class="button-blacklist">Dodaj do czarnej listy</button>
            <button class="button-whitelist">Dodaj do białej listy</button>
        </div>
    </div>
    <div class="results-container hide before-searching">
    </div>
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

{% block javascript %}
    <script src="js/modal.js"></script>
{% endblock %}

templates/file_upload.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/file_upload.css' %}">
{% endblock %}

{% block content %}

    {% comment %} <div>
    <form action="">
    {{ single_form }}
    </form>
    </div> {% endcomment %}


    <div class="input-container">
        <div class="input-header">Import txt file with list of domains</div>
        <div>{{ form.errors }}</div>
        <form method="post" enctype="multipart/form-data" id="file-upload">
            {% csrf_token %}
            <div class="input-field">
                <div class="field-label">{{ form.domain_list.label }}</div>
                <div class="field-help">{{ form.domain_list.help_text }}</div>
                {{ form.domain_list }}
            </div>
            <div class="input-line">
                <div class="input-field delimiter">
                    <div class="field-label">{{ form.delimiter.label }}</div>
                    {{ form.delimiter }}
                </div>
                <div class="input-field list">
                    <div class="field-label"> {{ form.list.label }}</div>
                    {{ form.list }}
                </div>
                <div class="input-field submit">
                    <input type="submit" value="Import">
                </div>
            </div>
        </form>
    </div>
    <div class="results-container before-uploading">
        <table class="domain-table hide">
            <tr>
                <th>Domain name</th>
                <th>Harmless</th>
                <th>Suspicious</th>
                <th>Malicious</th>
                <th>Undetected</th>
                <th>Action</th>
                <th>Action result</th>
            </tr>
        </table>
    </div>
{% endblock %}


<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

{% block javascript %}
    <script>
        const icon_ok = `<img src="{% static 'img/icons/icons8-checkmark-48.png' %}">`;
        const icon_error = `<img src="{% static 'img/icons/icons8-delete-48.png' %}">`;
    </script>
    <script src="{% static 'js/add_single.js' %}"></script>
    <script src="{% static 'js/file_import.js' %}"></script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="input-container">
        <div class="input-header">Enter domain name and check its credibility</div>
        <div class="input-field">
            <button class="input-icon" id="search-button">
                <img src="{% static 'img/icons/icons8-search-48.png' %}">
            </button>
            <input type="text" id="search-input">
        </div>
    </div>
    <div class="results-container before-searching">
    </div>
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

{% block javascript %}
    <script src="{% static 'js/modal.js' %}"></script>
    <script>
    const domain_data = {}

    $("#search-button").on("click", () => {

        const domain = $("#search-input").val();

        $.get({
            url: "/api/domain",
            data: {
                domain: domain
            },
            dataType: "json"
        })
        .done((response) => {
            console.log(response);
            
            /*
            const domain_data = {
                "name": response.domain,
                "page_rank": response.data.page_rank_decimal,
                "error": response.data.error
            }

            const template = `
                ${
                    domain_data.page_rank > 6 ?
                    `<div class="results-bar state-ok">OK, rating strony ${domain_data.page_rank}</div>` :
                    domain_data.page_rank > 4 ?
                    `<div class="results-bar state-warning">Potencjalnie niebezpieczna, rating strony ${domain_data.page_rank}</div>` :
                    `<div class="results-bar state-danger">Niebezpieczna, rating strony ${domain_data.page_rank}</div>`
                }

                <div class="results-header">Wyniki wyszukiwania dla domeny ${domain_data.name}</div>
                <div class="results-buttons">
                    <button class="button-blacklist">Dodaj do czarnej listy</button>
                    <button class="button-whitelist">Dodaj do białej listy</button>
                </div>
                `;
            */
            
            domain_data.name = response.domain;
            domain_data.summary = [response.data.summary.harmless, response.data.summary.suspicious, response.data.summary.malicious, response.data.summary.undetected];
            domain_data.sum = domain_data.summary.reduce((a, b) => a + b, 0);
            domain_data.avgs = domain_data.summary.map((a) => a = Math.round(100 * a / domain_data.sum))

            const template = `
                <div class="results-bar state-ok">OK</div>
                <!-- <div class="results-bar state-warning">Potentially dangerous</div> -->
                <!-- <div class="results-bar state-danger">Niebezpieczna</div> -->

                <div class="results-header">Results for ${domain_data.name}</div>
                <div class="results-items">
                    <div class="results-item">
                        <div class="result-item-header">Result from antivirus engines</div>
                        <div class="result-item-subheader">(Click to see details)</div>
                        <div class="stats">
                            <div class="stat stat-ok" onclick="openModal(this)">
                                <div class="stat-icon"><img src="{% static 'img/icons/icons8-happy-48.png' %}"></div>
                                <div class="stat-desc">Secure</div>
                                <div class="stat-val">${domain_data.summary[0]} (${domain_data.avgs[0]}%)</div>
                            </div>
                            <div class="modal">
                                <div class="modal-wrapper">
                                    <div class="modal-content">
                                        <div class="modal-header stat-ok">
                                            Sites recognizing domain ${domain_data.name} as secure.
                                        </div>
                                        <ul class="modal-list">
                                            ${Object.keys(response.data)
                                                    .filter((el) => { return response.data[el].category === "harmless" })
                                                    .map((el) => `<li>${el}</li>`)
                                                    .join(' ')
                                            }
                                        </ul>
                                        <div class="modal-close" onclick="closeModal(this)"><img src="{% static 'img/icons/icons8-cancel-48.png' %}"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="stat stat-warning" onclick="openModal(this)">
                                <div class="stat-icon"><img src="{% static 'img/icons/icons8-boring-48.png' %}"></div>
                                <div class="stat-desc">Suspicious</div>
                                <div class="stat-val">${domain_data.summary[1]} (${domain_data.avgs[1]}%)</div>
                            </div>
                            <div class="modal">
                                <div class="modal-wrapper">
                                    <div class="modal-content">
                                        <div class="modal-header stat-warning">
                                            Sites recognizing domain ${domain_data.name} as suspicious.
                                        </div>
                                        <ul class="modal-list">
                                            ${Object.keys(response.data)
                                                .filter((el) => { return response.data[el].category === "suspicious" })
                                                .map((el) => `<li>${el}</li>`)
                                                .join(' ')
                                            }
                                        </ul>
                                        <div class="modal-close" onclick="closeModal(this)"><img src="{% static 'img/icons/icons8-cancel-48.png' %}"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="stat stat-danger" onclick="openModal(this)">
                                <div class="stat-icon"><img src="{% static 'img/icons/icons8-sad-48.png' %}"></div>
                                <div class="stat-desc">Dangerous</div>
                                <div class="stat-val">${domain_data.summary[2]} (${domain_data.avgs[2]}%)</div>
                            </div>
                            <div class="modal">
                                <div class="modal-wrapper">
                                    <div class="modal-content">
                                        <div class="modal-header stat-danger">
                                            Sites recognizing domain ${domain_data.name} as dangerous.
                                        </div>
                                        <ul class="modal-list">
                                            ${Object.keys(response.data)
                                                .filter((el) => { return response.data[el].category === "malicious" })
                                                .map((el) => `<li>${el}</li>`)
                                                .join(' ')
                                            }
                                        </ul>
                                        <div class="modal-close" onclick="closeModal(this)"><img src="{% static 'img/icons/icons8-cancel-48.pn' %}g"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="stat" onclick="openModal(this)">
                                <div class="stat-icon"><img src="{% static 'img/icons/icons8-puzzled-48.png' %}"></div>
                                <div class="stat-desc">N</div>
                                <div class="stat-val">${domain_data.summary[3]} (${domain_data.avgs[3]}%)</div>
                            </div>
                            <div class="modal">
                                <div class="modal-wrapper">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            Sites which could not verify domain ${domain_data.name}.
                                        </div>
                                        <ul class="modal-list">
                                            ${Object.keys(response.data)
                                                .filter((el) => { return response.data[el].category === "undetected" })
                                                .map((el) => `<li>${el}</li>`)
                                                .join(' ')
                                            }
                                        </ul>
                                        <div class="modal-close" onclick="closeModal(this)"><img src="{% static 'img/icons/icons8-cancel-48.png' %}"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="results-item">
                        <div class="result-item-header">WHOIS results</div>
                        <div class="whois">${response.data.whois.split("\n").join("<br>")}</div>
                    </div>
                </div>
                <div class="results-buttons">
                    <select class="list">
                        {% for list in lists %}
                            <option value={{ list.id }}>{{ list.name }}</option>
                        {% endfor %}
                    </select>
                    <button class="button-blacklist" onclick="addSingle(this)">Add to blacklist</button>
                    <button class="button-whitelist" onclick="addSingle(this)">Add to whitelist</button>
                </div>
                `;
                

                $(".results-container").removeClass("before-searching");
                $(".results-container").html(template);

            })
            .fail(() => {
                console.log("error");
            })

        });
    </script>
    <script src="{% static 'js/add_single.js' %}"></script>
{% endblock %}

templates/list_form.html
<form action="{% if form.instance.pk %}{% url 'list_update' %}{% else %}{% url 'list_create' %}{% endif %}" method="post">
    {{ form.name.errors }}
    {{ form.name.label }} {{ form.name }}
    <button>Submit</button>
</form>